### ISSUE TITLE
Tracking issue: Tact v1.4.0

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact-sublime#14]
To be resolved by #15:
- [x] Bitwise NOT `~`
- [x] New augmented assignment operators: `|=`, `&=`, `^=`
- [x] Underscores `_` as unused variable identifiers
- [x] Local type inference for `let` statements
- [x] nativeThrowWhen renamed to nativeThrowIf

Other things:
- [x] Create a new release: https://github.com/tact-lang/tact-sublime/releases/tag/v1.4.0

**Comment by novusnota** [comment]
Done!
